on: [push, pull_request]
name: Playbook

permissions:
  contents: read

jobs:
  Playbook:
    name: Playbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Print env
        run: |
          env

