on: [push, pull_request]
name: Playbook

permissions:
  contents: read

jobs:
  Playbook:
    name: Playbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install uv and run playbook
        env:
          ANSIBLE_LIBRARY: "${GITHUB_WORKSPACE}"
          ANSIBLE_TOKEN: "${{ secrets.ANSIBLE }}"
        run: |
          sudo apt-get update
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          source .venv/bin/activate
          uv pip install -U ansible ansible-lint passlib
          uv pip install -U -r requirements.txt
          ansible-playbook -i 'localhost,' -c local playbook.yml
